clear all; fclose all; clc;

%% Sinogram Sizes
% nRad=95; nAng=48; nPlanes=64; %24 Ring 
nRad=47; nAng=24; nPlanes=64; %12 Ring 
% g.nRad=59; g.nAng=48; g.nPlanes=64; %truncated dimensions used by Nicolas at Cornell

%% Creating Directories
sino_input_folder = ['C:\Users\louis\Documents\STIR-overall\12 Ring Reconstruction\T0 Flood\']; %directory where the sinogram files generated by PETshop are 
sino_mat_file = ['study_20191031T165048_0080_sino.mat']; %name of the sinogram mat file
input_sino_mat_file = [sino_input_folder sino_mat_file]; %generates the full path of the sinogram mat file

sino_output_folder=['STIR-formatted sinograms\']; %name of the sub-directory where the STIR-formatted sinogram file will be archived, as well as the final image
output_sino_fullpath = [sino_input_folder sino_output_folder] %generates the full path of the output folder

mkdir(output_sino_fullpath)
cd(output_sino_fullpath)

%% Generate interfile format sinograms
load(input_sino_mat_file,'stat', 'recordinfo', 'sino', 'sino_rand'); %loads sinogram data
sino=reshape(sino,nRad,nAng,nPlanes); %reshapes prompts sino array into proper dimensions
sino_rand= reshape(sino_rand,nRad,nAng,nPlanes); %reshapes randoms sino array into proper dimensions

fid = fopen(sprintf('%s\\sino_12R_prompts.s',output_sino_fullpath), 'wb'); %creates prompts in interfile format
fwrite(fid,sino,'float32');
fclose(fid);

fid = fopen(sprintf('%s\\sino_12R_randoms.s',output_sino_fullpath), 'wb'); %creates randoms in interfile format
fwrite(fid,sino_rand,'float32');
fclose(fid);

%% Copy STIR Template Files to working directory
copyfile 'C:\Users\louis\Documents\STIR-overall\Template Files\12_Ring'
% files copied:
% sino_template.hs
% OSMAPOSL_Template.hs
% mango-convert2dcm.bat

%% Fill Template Files
FILENAME = 'sino_12R'; %Change for 24 Ring

%Fills OSMAPOSL_Template to create OSMAPOSL_Run.par
par_template = fileread('OSMAPOSL_Template.par'); %Reads par template file
par_template_fixed = regexprep(par_template,'FILENAME',FILENAME); %Replaces any instance of "FILENAME" in OSMAPOSL_Template.par with "sino_12R" (or "sino_24R")
fid = fopen('OSMAPOSL_Run.par','w'); %Creates fixed .par file
fwrite(fid , par_template_fixed); %Writes fixed text to new .par file

%Fills sino_template to create prompts.hs
sino_template = fileread('sino_template.hs'); %Reads sino template file
sino_template_prompts = regexprep(sino_template,'FILENAME',sprintf('%s_prompts', FILENAME)); %Replaces any instance of "FILENAME" in sino_template.hs with sino "sino_12R_prompts" (or "sino_24R_prompts")
fid = fopen(sprintf('%s_prompts.hs',FILENAME),'w'); %Creates prompts.hs file
fwrite(fid , sino_template_prompts); %Writes fixed text to new prompts.hs file

%Fills sino_template to create randoms.hs
sino_template_randoms = regexprep(sino_template,'FILENAME',sprintf('%s_randoms', FILENAME)); %Replaces any instance of "FILENAME" in sino_template.hs with sino "sino_12R_randoms" (or "sino_24R_randoms")
fid = fopen(sprintf('%s_randoms.hs',FILENAME),'w'); %Creates randoms.hs file
fwrite(fid , sino_template_randoms); %Writes fixed text to new randoms.hs file

%% Execute STIR Recon 
system('bash -c "OSMAPOSL OSMAPOSL_Run.par"'); %Performs the STIR Reconstruction
delete *.v *.hv *.ahv  %Removes extra files created by STIR

%% Convert to DICOM and Open Mango
%system(sprintf('call mango-convert2dcm -pet -out %s_img_24.dcm %s_img_24.nii',FILENAME, FILENAME)); %creates a DICOM image 
%system(sprintf('call mango-mango %s_img_24.dcm',FILENAME)); %opens mango

V = niftiread(sprintf('%s_img_24.nii',FILENAME));
info = niftiinfo(sprintf('%s_img_24.nii',FILENAME));
whos V
info.Version
info.PixelDimensions
info.raw
volshow(V);

